import { TestItem } from "../drizzle/schema";

// 要件定義書に基づく全検査項目リスト（ダミーデータ用）
// このファイルは server/db.ts の getDummyTestItems() 関数で使用されます
export const dummyTestItemsData: Omit<TestItem, "id" | "createdAt" | "updatedAt">[] = [
  // ①身体
  { itemCode: "HEIGHT", itemName: "身長", category: "身体", unit: "cm", referenceMin: null, referenceMax: null, displayOrder: 1, notes: null },
  { itemCode: "WEIGHT", itemName: "体重", category: "身体", unit: "kg", referenceMin: null, referenceMax: null, displayOrder: 2, notes: null },
  { itemCode: "BMI", itemName: "BMI", category: "身体", unit: "", referenceMin: "18.5", referenceMax: "24.9", displayOrder: 3, notes: null },
  { itemCode: "WAIST", itemName: "腹囲", category: "身体", unit: "cm", referenceMin: null, referenceMax: null, displayOrder: 4, notes: null },
  { itemCode: "BODY_FAT", itemName: "体脂肪率", category: "身体", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 5, notes: null },
  { itemCode: "LEAN_BODY_MASS", itemName: "除脂肪率", category: "身体", unit: "kg", referenceMin: null, referenceMax: null, displayOrder: 6, notes: null },
  { itemCode: "BMR", itemName: "基礎代謝量", category: "身体", unit: "kcal/day", referenceMin: null, referenceMax: null, displayOrder: 7, notes: null },
  { itemCode: "VISION_NAKED_R", itemName: "視力裸眼 (右)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 8, notes: null },
  { itemCode: "VISION_NAKED_L", itemName: "視力裸眼 (左)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 9, notes: null },
  { itemCode: "VISION_CORRECTED_R", itemName: "視力矯正 (右)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 10, notes: null },
  { itemCode: "VISION_CORRECTED_L", itemName: "視力矯正 (左)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 11, notes: null },
  { itemCode: "HEARING_4K_R", itemName: "聴力 (4000Hz,右)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 12, notes: null },
  { itemCode: "HEARING_4K_L", itemName: "聴力 (4000Hz,左)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 13, notes: null },
  { itemCode: "HEARING_1K_R", itemName: "聴力 (1000Hz,右)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 14, notes: null },
  { itemCode: "HEARING_1K_L", itemName: "聴力 (1000Hz,左)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 15, notes: null },
  { itemCode: "IOP_R", itemName: "眼圧 (右)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 16, notes: null },
  { itemCode: "IOP_L", itemName: "眼圧 (左)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 17, notes: null },
  { itemCode: "IOP_CORRECTED_R", itemName: "修正眼圧 (右)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 18, notes: null },
  { itemCode: "IOP_CORRECTED_L", itemName: "修正眼圧 (左)", category: "身体", unit: "", referenceMin: null, referenceMax: null, displayOrder: 19, notes: null },
  { itemCode: "Z_SCORE", itemName: "同年齢比較(Z値)", category: "身体", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 20, notes: null },
  { itemCode: "YAM_T_SCORE", itemName: "若年比較(YAM,t値)", category: "身体", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 21, notes: null },

  // ②脳・血管
  { itemCode: "CAROTID_ECHO", itemName: "頸動脈エコー", category: "脳・血管", unit: "", referenceMin: null, referenceMax: null, displayOrder: 30, notes: null },
  { itemCode: "HEAD_MRI_MRA", itemName: "頭部MRI/MRA", category: "脳・血管", unit: "", referenceMin: null, referenceMax: null, displayOrder: 31, notes: null },
  { itemCode: "ODI", itemName: "血中酸素ウェルネス低下指数(ODI)", category: "脳・血管", unit: "回", referenceMin: null, referenceMax: null, displayOrder: 32, notes: null },
  { itemCode: "SLEEP_STABILITY", itemName: "睡眠の安定度", category: "脳・血管", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 33, notes: null },

  // ③肺機能
  { itemCode: "VC", itemName: "肺活量", category: "肺機能", unit: "L", referenceMin: null, referenceMax: null, displayOrder: 40, notes: null },
  { itemCode: "PERCENT_VC", itemName: "%肺活量(%VC)", category: "肺機能", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 41, notes: null },
  { itemCode: "FEV1", itemName: "1秒量(FEV1)", category: "肺機能", unit: "L", referenceMin: null, referenceMax: null, displayOrder: 42, notes: null },
  { itemCode: "PERCENT_FEV1", itemName: "%1秒量(%FEV1)", category: "肺機能", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 43, notes: null },
  { itemCode: "FEV1_PERCENT", itemName: "1秒率(FEV1%)", category: "肺機能", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 44, notes: null },
  { itemCode: "FVC", itemName: "努力性肺活量(FVC)", category: "肺機能", unit: "L", referenceMin: null, referenceMax: null, displayOrder: 45, notes: null },
  { itemCode: "PEF", itemName: "ピークフロー", category: "肺機能", unit: "L/sec", referenceMin: null, referenceMax: null, displayOrder: 46, notes: null },
  { itemCode: "PRED_VC", itemName: "予測肺活量", category: "肺機能", unit: "L", referenceMin: null, referenceMax: null, displayOrder: 47, notes: null },
  { itemCode: "KL6", itemName: "KL-6", category: "肺機能", unit: "", referenceMin: null, referenceMax: null, displayOrder: 48, notes: null },

  // ④血圧
  { itemCode: "SBP", itemName: "収縮期血圧", category: "血圧", unit: "mmHg", referenceMin: "90", referenceMax: "139", displayOrder: 50, notes: null },
  { itemCode: "DBP", itemName: "拡張期血圧", category: "血圧", unit: "mmHg", referenceMin: "60", referenceMax: "89", displayOrder: 51, notes: null },

  // ⑤血液
  { itemCode: "RBC", itemName: "赤血球数", category: "血液", unit: "x10^6/µL", referenceMin: null, referenceMax: null, displayOrder: 60, notes: null },
  { itemCode: "HGB", itemName: "Hb", category: "血液", unit: "g/dL", referenceMin: "13.0", referenceMax: "17.0", displayOrder: 61, notes: null },
  { itemCode: "HCT", itemName: "Ht", category: "血液", unit: "%", referenceMin: "40.0", referenceMax: "52.0", displayOrder: 62, notes: null },
  { itemCode: "FE", itemName: "鉄", category: "血液", unit: "µg/dL", referenceMin: null, referenceMax: null, displayOrder: 63, notes: null },
  { itemCode: "FERRITIN", itemName: "フェリチン", category: "血液", unit: "ng/mL", referenceMin: null, referenceMax: null, displayOrder: 64, notes: null },
  { itemCode: "RETIC", itemName: "網状赤血球", category: "血液", unit: "", referenceMin: null, referenceMax: null, displayOrder: 65, notes: null },
  { itemCode: "LDH", itemName: "LDH", category: "血液", unit: "U/L", referenceMin: "120", referenceMax: "240", displayOrder: 66, notes: null },
  { itemCode: "WBC", itemName: "白血球数", category: "血液", unit: "x10^3/µL", referenceMin: "3.5", referenceMax: "9.0", displayOrder: 67, notes: null },
  { itemCode: "NEUTROPHIL", itemName: "好中球", category: "血液", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 68, notes: null },
  { itemCode: "LYMPHOCYTE", itemName: "リンパ球", category: "血液", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 69, notes: null },
  { itemCode: "MONOCYTE", itemName: "単球", category: "血液", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 70, notes: null },
  { itemCode: "EOSINOPHIL", itemName: "好酸球", category: "血液", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 71, notes: null },
  { itemCode: "BASOPHIL", itemName: "好塩基球", category: "血液", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 72, notes: null },
  { itemCode: "PLT", itemName: "血小板数", category: "血液", unit: "x10^4/µL", referenceMin: "14.0", referenceMax: "37.9", displayOrder: 73, notes: null },
  { itemCode: "MCV", itemName: "MCV", category: "血液", unit: "fL", referenceMin: "83", referenceMax: "102", displayOrder: 74, notes: null },
  { itemCode: "MCH", itemName: "MCH", category: "血液", unit: "pg", referenceMin: "28", referenceMax: "34", displayOrder: 75, notes: null },
  { itemCode: "MCHC", itemName: "MCHC", category: "血液", unit: "%", referenceMin: "32", referenceMax: "36", displayOrder: 76, notes: null },
  { itemCode: "TIBC", itemName: "総鉄結合能(TIBC)", category: "血液", unit: "μg/dL", referenceMin: null, referenceMax: null, displayOrder: 77, notes: null },
  { itemCode: "UIBC", itemName: "不飽和鉄結合能(UIBC)", category: "血液", unit: "μg/dL", referenceMin: null, referenceMax: null, displayOrder: 78, notes: null },
  { itemCode: "ABO", itemName: "ABO", category: "血液", unit: "", referenceMin: null, referenceMax: null, displayOrder: 79, notes: null },
  { itemCode: "RH", itemName: "RH", category: "血液", unit: "", referenceMin: null, referenceMax: null, displayOrder: 80, notes: null },

  // ⑥脂質代謝
  { itemCode: "TC", itemName: "総コレステロール", category: "脂質代謝", unit: "mg/dL", referenceMin: "120", referenceMax: "219", displayOrder: 90, notes: null },
  { itemCode: "HDL", itemName: "HDLコレステロール", category: "脂質代謝", unit: "mg/dL", referenceMin: "40", referenceMax: "119", displayOrder: 91, notes: null },
  { itemCode: "LDL", itemName: "LDLコレステロール", category: "脂質代謝", unit: "mg/dL", referenceMin: "60", referenceMax: "139", displayOrder: 92, notes: null },
  { itemCode: "L_H_RATIO", itemName: "L/H比", category: "脂質代謝", unit: "", referenceMin: null, referenceMax: null, displayOrder: 93, notes: null },
  { itemCode: "NON_HDL", itemName: "non-HDLコレステロール", category: "脂質代謝", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 94, notes: null },
  { itemCode: "SD_LDL", itemName: "sd-LDL", category: "脂質代謝", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 95, notes: null },
  { itemCode: "TG", itemName: "空腹時中性脂肪", category: "脂質代謝", unit: "mg/dL", referenceMin: "30", referenceMax: "149", displayOrder: 96, notes: null },
  { itemCode: "NT_PROBNP", itemName: "NT-proBNP", category: "脂質代謝", unit: "", referenceMin: null, referenceMax: null, displayOrder: 97, notes: null },

  // ⑦糖代謝
  { itemCode: "GLU", itemName: "空腹時血糖", category: "糖代謝", unit: "mg/dL", referenceMin: "70", referenceMax: "109", displayOrder: 100, notes: null },
  { itemCode: "HBA1C", itemName: "HbA1c", category: "糖代謝", unit: "%", referenceMin: "4.6", referenceMax: "6.2", displayOrder: 101, notes: null },
  { itemCode: "ONE_5_AG", itemName: "1,5-AG", category: "糖代謝", unit: "µg/mL", referenceMin: null, referenceMax: null, displayOrder: 102, notes: null },
  { itemCode: "GA", itemName: "グリコアルブミン", category: "糖代謝", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 103, notes: null },
  { itemCode: "GLU_2H", itemName: "食後2時間血糖", category: "糖代謝", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 104, notes: null },

  // ⑧腎・尿路系
  { itemCode: "U_PRO", itemName: "尿蛋白", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 110, notes: null },
  { itemCode: "U_BLD", itemName: "尿潜血", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 111, notes: null },
  { itemCode: "U_GLU", itemName: "尿糖", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 112, notes: null },
  { itemCode: "U_UBG", itemName: "尿中ウロビリノーゲン", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 113, notes: null },
  { itemCode: "U_PH", itemName: "尿pH", category: "腎・尿路系", unit: "", referenceMin: "5.0", referenceMax: "7.5", displayOrder: 114, notes: null },
  { itemCode: "U_SG", itemName: "尿比重", category: "腎・尿路系", unit: "", referenceMin: "1.010", referenceMax: "1.025", displayOrder: 115, notes: null },
  { itemCode: "UA", itemName: "尿酸", category: "腎・尿路系", unit: "mg/dL", referenceMin: "3.0", referenceMax: "7.0", displayOrder: 116, notes: null },
  { itemCode: "BUN", itemName: "尿素窒素", category: "腎・尿路系", unit: "mg/dL", referenceMin: "8", referenceMax: "20", displayOrder: 117, notes: null },
  { itemCode: "CRE", itemName: "クレアチニン", category: "腎・尿路系", unit: "mg/dL", referenceMin: "0.6", referenceMax: "1.2", displayOrder: 118, notes: null },
  { itemCode: "EGFR", itemName: "eGFR", category: "腎・尿路系", unit: "mL/min/1.73m2", referenceMin: "60", referenceMax: "120", displayOrder: 119, notes: null },
  { itemCode: "NA", itemName: "Na", category: "腎・尿路系", unit: "mEq/L", referenceMin: null, referenceMax: null, displayOrder: 120, notes: null },
  { itemCode: "K", itemName: "K", category: "腎・尿路系", unit: "mEq/L", referenceMin: null, referenceMax: null, displayOrder: 121, notes: null },
  { itemCode: "CL", itemName: "Cl", category: "腎・尿路系", unit: "mEq/L", referenceMin: null, referenceMax: null, displayOrder: 122, notes: null },
  { itemCode: "U_ALB", itemName: "尿中アルブミン", category: "腎・尿路系", unit: "mg/gCre", referenceMin: null, referenceMax: null, displayOrder: 123, notes: null },
  { itemCode: "U_WBC", itemName: "白血球（尿沈渣）", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 124, notes: null },
  { itemCode: "U_RBC", itemName: "赤血球（尿沈渣）", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 125, notes: null },
  { itemCode: "U_SQUAMOUS", itemName: "扁平上皮（尿沈渣）", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 126, notes: null },
  { itemCode: "U_TRANSITIONAL", itemName: "尿路上皮（尿沈渣）", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 127, notes: null },
  { itemCode: "U_CAST", itemName: "円柱（尿沈渣）", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 128, notes: null },
  { itemCode: "U_BACTERIA", itemName: "細菌（尿沈渣）", category: "腎・尿路系", unit: "", referenceMin: null, referenceMax: null, displayOrder: 129, notes: null },
  { itemCode: "L_FABP", itemName: "L-FABP", category: "腎・尿路系", unit: "μg/gCre", referenceMin: null, referenceMax: null, displayOrder: 130, notes: null },

  // ⑨肝胆膵（続きは次のコメントで）
  { itemCode: "AST", itemName: "AST", category: "肝胆膵", unit: "U/L", referenceMin: "10", referenceMax: "40", displayOrder: 140, notes: null },
  { itemCode: "ALT", itemName: "ALT", category: "肝胆膵", unit: "U/L", referenceMin: "5", referenceMax: "45", displayOrder: 141, notes: null },
  { itemCode: "GGT", itemName: "γ-GTP", category: "肝胆膵", unit: "U/L", referenceMin: "0", referenceMax: "79", displayOrder: 142, notes: null },
  { itemCode: "T_BIL", itemName: "総ビリルビン", category: "肝胆膵", unit: "mg/dL", referenceMin: "0.2", referenceMax: "1.2", displayOrder: 143, notes: null },
  { itemCode: "D_BIL", itemName: "直接ビリルビン", category: "肝胆膵", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 144, notes: null },
  { itemCode: "I_BIL", itemName: "間接ビリルビン", category: "肝胆膵", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 145, notes: null },
  { itemCode: "CPK", itemName: "CPK", category: "肝胆膵", unit: "U/L", referenceMin: null, referenceMax: null, displayOrder: 146, notes: null },
  { itemCode: "CHE", itemName: "Ch-E", category: "肝胆膵", unit: "U/L", referenceMin: null, referenceMax: null, displayOrder: 147, notes: null },
  { itemCode: "TP", itemName: "総蛋白", category: "肝胆膵", unit: "g/dL", referenceMin: "6.5", referenceMax: "8.2", displayOrder: 148, notes: null },
  { itemCode: "A_G_RATIO", itemName: "A/G比", category: "肝胆膵", unit: "", referenceMin: null, referenceMax: null, displayOrder: 149, notes: null },
  { itemCode: "ALB", itemName: "アルブミン量", category: "肝胆膵", unit: "g/dL", referenceMin: "3.8", referenceMax: "5.3", displayOrder: 150, notes: null },
  { itemCode: "AMY", itemName: "アミラーゼ", category: "肝胆膵", unit: "U/L", referenceMin: null, referenceMax: null, displayOrder: 151, notes: null },
  { itemCode: "HBS_AG", itemName: "HBs抗原", category: "肝胆膵", unit: "定性", referenceMin: null, referenceMax: null, displayOrder: 152, notes: null },
  { itemCode: "HCV_AB", itemName: "HCV抗体", category: "肝胆膵", unit: "", referenceMin: null, referenceMax: null, displayOrder: 153, notes: null },
  { itemCode: "LDH2", itemName: "LDH", category: "肝胆膵", unit: "U/L", referenceMin: "120", referenceMax: "240", displayOrder: 154, notes: null },
  { itemCode: "ALP", itemName: "ALP", category: "肝胆膵", unit: "U/L", referenceMin: "100", referenceMax: "340", displayOrder: 155, notes: null },
  { itemCode: "CERULOPLASMIN", itemName: "セルロプラスミン", category: "肝胆膵", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 156, notes: null },
  { itemCode: "PROT_ALB", itemName: "蛋白分画(アルブミン)", category: "肝胆膵", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 157, notes: null },
  { itemCode: "PROT_A1", itemName: "蛋白分画(α1)", category: "肝胆膵", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 158, notes: null },
  { itemCode: "PROT_A2", itemName: "蛋白分画(α2)", category: "肝胆膵", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 159, notes: null },
  { itemCode: "PROT_B1", itemName: "蛋白分画(β1)", category: "肝胆膵", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 160, notes: null },
  { itemCode: "PROT_B2", itemName: "蛋白分画(β2)", category: "肝胆膵", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 161, notes: null },
  { itemCode: "PROT_G", itemName: "蛋白分画(γ)", category: "肝胆膵", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 162, notes: null },
  { itemCode: "FIB4", itemName: "FIB-4 index", category: "肝胆膵", unit: "", referenceMin: null, referenceMax: null, displayOrder: 163, notes: null },
  { itemCode: "ZN", itemName: "亜鉛", category: "肝胆膵", unit: "μg/dL", referenceMin: null, referenceMax: null, displayOrder: 164, notes: null },
  { itemCode: "MG", itemName: "マグネシウム", category: "肝胆膵", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 165, notes: null },
  { itemCode: "CU", itemName: "血清銅", category: "肝胆膵", unit: "μg/dL", referenceMin: null, referenceMax: null, displayOrder: 166, notes: null },
  { itemCode: "IP", itemName: "無機リン", category: "肝胆膵", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 167, notes: null },
  { itemCode: "25OHVD", itemName: "25OHVD", category: "肝胆膵", unit: "μg/mL", referenceMin: null, referenceMax: null, displayOrder: 168, notes: null },
  { itemCode: "ONE_25_OH2VD", itemName: "1,25(OH)2VD", category: "肝胆膵", unit: "PG/mL", referenceMin: null, referenceMax: null, displayOrder: 169, notes: null },

  // ⑩内分泌
  { itemCode: "PL", itemName: "リン脂質", category: "内分泌", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 170, notes: null },
  { itemCode: "HOMOCYSTEINE", itemName: "総ホモシステイン", category: "内分泌", unit: "nmol/mL", referenceMin: null, referenceMax: null, displayOrder: 171, notes: null },
  { itemCode: "FFA", itemName: "遊離脂肪酸", category: "内分泌", unit: "μEq/L", referenceMin: null, referenceMax: null, displayOrder: 172, notes: null },
  { itemCode: "CA", itemName: "カルシウム", category: "内分泌", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 173, notes: null },
  { itemCode: "TSH", itemName: "TSH", category: "内分泌", unit: "μIU/mL", referenceMin: null, referenceMax: null, displayOrder: 174, notes: null },
  { itemCode: "FT3", itemName: "遊離T3", category: "内分泌", unit: "pg/mL", referenceMin: null, referenceMax: null, displayOrder: 175, notes: null },
  { itemCode: "FT4", itemName: "遊離T4", category: "内分泌", unit: "pg/mL", referenceMin: null, referenceMax: null, displayOrder: 176, notes: null },
  { itemCode: "THYROID_ECHO", itemName: "甲状腺エコー", category: "内分泌", unit: "", referenceMin: null, referenceMax: null, displayOrder: 177, notes: null },

  // ⑪口腔
  { itemCode: "CARIES", itemName: "齲歯本数", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 180, notes: null },
  { itemCode: "C0", itemName: "C0", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 181, notes: null },
  { itemCode: "C1", itemName: "C1", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 182, notes: null },
  { itemCode: "C2", itemName: "C2", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 183, notes: null },
  { itemCode: "C3", itemName: "C3", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 184, notes: null },
  { itemCode: "C4", itemName: "C4", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 185, notes: null },
  { itemCode: "MOBILE_TEETH", itemName: "動揺歯数", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 186, notes: null },
  { itemCode: "CALCULUS_TEETH", itemName: "歯石歯数", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 187, notes: null },
  { itemCode: "HEALTHY_TEETH", itemName: "健全歯数", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 188, notes: null },
  { itemCode: "PERIODONTAL_3", itemName: "歯周ポケットの深さが3以上の歯数", category: "口腔", unit: "", referenceMin: null, referenceMax: null, displayOrder: 189, notes: null },

  // ⑫診察
  { itemCode: "EXAM_FINDINGS", itemName: "診察所見", category: "診察", unit: "", referenceMin: null, referenceMax: null, displayOrder: 190, notes: null },

  // ⑬循環器
  { itemCode: "FUNDUS_FINDINGS", itemName: "眼底（所見）", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 200, notes: null },
  { itemCode: "FUNDUS_KW_R", itemName: "眼底（K-W）右", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 201, notes: null },
  { itemCode: "FUNDUS_KW_L", itemName: "眼底（K-W）左", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 202, notes: null },
  { itemCode: "FUNDUS_S_S_R", itemName: "眼底（Scheie S）右", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 203, notes: null },
  { itemCode: "FUNDUS_S_S_L", itemName: "眼底（Scheie S）左", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 204, notes: null },
  { itemCode: "FUNDUS_S_H_R", itemName: "眼底（Scheie H）右", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 205, notes: null },
  { itemCode: "FUNDUS_S_H_L", itemName: "眼底（Scheie H）左", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 206, notes: null },
  { itemCode: "ECG", itemName: "安静時心電図", category: "循環器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 207, notes: null },
  { itemCode: "HR", itemName: "心拍数", category: "循環器", unit: "/min", referenceMin: null, referenceMax: null, displayOrder: 208, notes: null },

  // ⑭呼吸器
  { itemCode: "CHEST_XRAY", itemName: "胸部X線", category: "呼吸器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 210, notes: null },
  { itemCode: "CTR", itemName: "CTR(心胸郭比)", category: "呼吸器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 211, notes: null },
  { itemCode: "CHEST_CT", itemName: "胸部CT", category: "呼吸器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 212, notes: null },

  // ⑮消化器
  { itemCode: "ABD_ECHO_LIVER", itemName: "腹部エコー（肝臓所見）", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 220, notes: null },
  { itemCode: "ABD_ECHO_GB", itemName: "腹部エコー（胆嚢所見）", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 221, notes: null },
  { itemCode: "ABD_ECHO_PANCREAS", itemName: "腹部エコー（すい臓所見）", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 222, notes: null },
  { itemCode: "ABD_ECHO_KIDNEY", itemName: "腹部エコー（腎臓所見）", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 223, notes: null },
  { itemCode: "ABD_ECHO_SPLEEN", itemName: "腹部エコー（脾臓所見）", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 224, notes: null },
  { itemCode: "ABD_ECHO_AORTA", itemName: "腹部エコー（腹部大動脈）", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 225, notes: null },
  { itemCode: "EGD", itemName: "上部内視鏡所見", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 226, notes: null },
  { itemCode: "COLONOSCOPY", itemName: "下部内視鏡所見", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 227, notes: null },
  { itemCode: "UGI", itemName: "胃バリウム", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 228, notes: null },
  { itemCode: "FOBT1", itemName: "便潜血(1回目)", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 229, notes: null },
  { itemCode: "FOBT2", itemName: "便潜血(2回目)", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 230, notes: null },
  { itemCode: "PG1", itemName: "ペプシノーゲンⅠ", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 231, notes: null },
  { itemCode: "PG2", itemName: "ペプシノーゲンⅡ", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 232, notes: null },
  { itemCode: "PG_RATIO", itemName: "ペプシノーゲン比", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 233, notes: null },
  { itemCode: "HP_AB", itemName: "血清ピロリ抗体", category: "消化器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 234, notes: null },

  // ⑯生殖器
  { itemCode: "CERVICAL_CYTOLOGY", itemName: "子宮頸部細胞診", category: "生殖器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 240, notes: null },
  { itemCode: "HPV16", itemName: "HPV16", category: "生殖器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 241, notes: null },
  { itemCode: "HPV18", itemName: "HPV18", category: "生殖器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 242, notes: null },
  { itemCode: "HPV_OTHER", itemName: "HPVその他ハイリスクグループ", category: "生殖器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 243, notes: null },
  { itemCode: "TV_ECHO_UTERUS", itemName: "経腟エコー（子宮）", category: "生殖器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 244, notes: null },
  { itemCode: "TV_ECHO_OVARY", itemName: "経腟エコー（卵巣）", category: "生殖器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 245, notes: null },
  { itemCode: "PELVIC_MRI", itemName: "骨盤MRI", category: "生殖器", unit: "", referenceMin: null, referenceMax: null, displayOrder: 246, notes: null },

  // ⑰乳がん
  { itemCode: "MAMMO_R", itemName: "マンモグラフィー右", category: "乳がん", unit: "", referenceMin: null, referenceMax: null, displayOrder: 250, notes: null },
  { itemCode: "MAMMO_L", itemName: "マンモグラフィー左", category: "乳がん", unit: "", referenceMin: null, referenceMax: null, displayOrder: 251, notes: null },
  { itemCode: "BREAST_ECHO_R", itemName: "乳腺エコー右", category: "乳がん", unit: "", referenceMin: null, referenceMax: null, displayOrder: 252, notes: null },
  { itemCode: "BREAST_ECHO_L", itemName: "乳腺エコー左", category: "乳がん", unit: "", referenceMin: null, referenceMax: null, displayOrder: 253, notes: null },

  // ⑱腫瘍マーカー
  { itemCode: "CEA", itemName: "CEA", category: "腫瘍マーカー", unit: "", referenceMin: null, referenceMax: null, displayOrder: 260, notes: null },
  { itemCode: "CA199", itemName: "CA19-9", category: "腫瘍マーカー", unit: "", referenceMin: null, referenceMax: null, displayOrder: 261, notes: null },
  { itemCode: "PSA", itemName: "PSA (男性)", category: "腫瘍マーカー", unit: "", referenceMin: null, referenceMax: null, displayOrder: 262, notes: null },
  { itemCode: "CA125", itemName: "CA125 (女性)", category: "腫瘍マーカー", unit: "", referenceMin: null, referenceMax: null, displayOrder: 263, notes: null },
  { itemCode: "AFP", itemName: "AFP", category: "腫瘍マーカー", unit: "", referenceMin: null, referenceMax: null, displayOrder: 264, notes: null },
  { itemCode: "SCC", itemName: "SCC抗原", category: "腫瘍マーカー", unit: "", referenceMin: null, referenceMax: null, displayOrder: 265, notes: null },
  { itemCode: "CYFRA", itemName: "CYFRA", category: "腫瘍マーカー", unit: "", referenceMin: null, referenceMax: null, displayOrder: 266, notes: null },

  // ⑲感染症・免疫（主要項目のみ、MAST48アレルゲンは省略）
  { itemCode: "CRP", itemName: "CRP", category: "感染症・免疫", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 270, notes: null },
  { itemCode: "ESR", itemName: "赤沈", category: "感染症・免疫", unit: "mm/1h", referenceMin: null, referenceMax: null, displayOrder: 271, notes: null },
  { itemCode: "RF", itemName: "RF", category: "感染症・免疫", unit: "IU/mL", referenceMin: null, referenceMax: null, displayOrder: 272, notes: null },
  { itemCode: "ANA", itemName: "抗核抗体", category: "感染症・免疫", unit: "倍", referenceMin: null, referenceMax: null, displayOrder: 273, notes: null },
  { itemCode: "MPO_ANCA", itemName: "MPO-ANCA", category: "感染症・免疫", unit: "U/mL", referenceMin: null, referenceMax: null, displayOrder: 274, notes: null },
  { itemCode: "PR3_ANCA", itemName: "PR3-ANCA", category: "感染症・免疫", unit: "U/mL", referenceMin: null, referenceMax: null, displayOrder: 275, notes: null },
  { itemCode: "CCP_AB", itemName: "抗CCP抗体", category: "感染症・免疫", unit: "U/mL", referenceMin: null, referenceMax: null, displayOrder: 276, notes: null },
  { itemCode: "HIV_AB", itemName: "HIV抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 277, notes: null },
  { itemCode: "TP_AB", itemName: "TP抗体", category: "感染症・免疫", unit: "定性", referenceMin: null, referenceMax: null, displayOrder: 278, notes: null },
  { itemCode: "RPR", itemName: "RPR", category: "感染症・免疫", unit: "定性", referenceMin: null, referenceMax: null, displayOrder: 279, notes: null },
  { itemCode: "SYPHILIS_AB", itemName: "梅毒抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 280, notes: null },
  { itemCode: "HBC_AB", itemName: "HBc抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 281, notes: null },
  { itemCode: "HCV_AB2", itemName: "HCV抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 282, notes: null },
  { itemCode: "CMV_AB", itemName: "サイトメガロウイルス抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 283, notes: null },
  { itemCode: "EBV_AB", itemName: "EBウイルス抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 284, notes: null },
  { itemCode: "MYCOPLASMA_AB", itemName: "マイコプラズマ抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 285, notes: null },
  { itemCode: "CHLAMYDIA_AB", itemName: "クラミジア抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 286, notes: null },
  { itemCode: "INFLUENZA_AB", itemName: "インフルエンザ抗体", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 287, notes: null },
  { itemCode: "MEASLES_AB", itemName: "麻疹抗体(EIA法-IgG)", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 288, notes: null },
  { itemCode: "MEASLES_AB_RESULT", itemName: "麻疹抗体(EIA-IgG)判定", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 289, notes: null },
  { itemCode: "RUBELLA_AB", itemName: "風疹抗体 (EIA法-IgG)", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 290, notes: null },
  { itemCode: "RUBELLA_AB_RESULT", itemName: "風疹抗体 (EIA法-IgG)判定", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 291, notes: null },
  { itemCode: "VARICELLA_AB", itemName: "水痘抗体(EIA法-IgG)", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 292, notes: null },
  { itemCode: "VARICELLA_AB_RESULT", itemName: "水痘抗体(EIA法-IgG)判定", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 293, notes: null },
  { itemCode: "MUMPS_AB", itemName: "ムンプス抗体(EIA法-IgG)", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 294, notes: null },
  { itemCode: "MUMPS_AB2", itemName: "ムンプス抗体(EIA法-IgG)", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 295, notes: null },
  { itemCode: "ASO", itemName: "ASO", category: "感染症・免疫", unit: "IU/mL", referenceMin: null, referenceMax: null, displayOrder: 296, notes: null },
  { itemCode: "ASK", itemName: "ASK", category: "感染症・免疫", unit: "IU/mL", referenceMin: null, referenceMax: null, displayOrder: 297, notes: null },
  { itemCode: "C3", itemName: "C3", category: "感染症・免疫", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 298, notes: null },
  { itemCode: "C4", itemName: "C4", category: "感染症・免疫", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 299, notes: null },
  { itemCode: "CH50", itemName: "CH50", category: "感染症・免疫", unit: "U/mL", referenceMin: null, referenceMax: null, displayOrder: 300, notes: null },
  { itemCode: "IGA", itemName: "IgA", category: "感染症・免疫", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 301, notes: null },
  { itemCode: "IGG", itemName: "IgG", category: "感染症・免疫", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 302, notes: null },
  { itemCode: "IGM", itemName: "IgM", category: "感染症・免疫", unit: "mg/dL", referenceMin: null, referenceMax: null, displayOrder: 303, notes: null },
  { itemCode: "IGE", itemName: "IgE", category: "感染症・免疫", unit: "IU/mL", referenceMin: null, referenceMax: null, displayOrder: 304, notes: null },
  { itemCode: "T_CELL", itemName: "T-cell", category: "感染症・免疫", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 305, notes: null },
  { itemCode: "B_CELL", itemName: "B-cell", category: "感染症・免疫", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 306, notes: null },
  { itemCode: "NK_CELL", itemName: "NK細胞", category: "感染症・免疫", unit: "%", referenceMin: null, referenceMax: null, displayOrder: 307, notes: null },
  
  // MAST48アレルゲン（主要なもののみ）
  { itemCode: "MAST_DERMATOPHAGOIDES_FARINAE", itemName: "ヤケヒョウヒダニ", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 310, notes: null },
  { itemCode: "MAST_DERMATOPHAGOIDES_PTERONYSSINUS", itemName: "コナヒョウヒダニ", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 311, notes: null },
  { itemCode: "MAST_HOUSE_DUST", itemName: "ハウスダスト", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 312, notes: null },
  { itemCode: "MAST_CEDAR", itemName: "スギ", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 313, notes: null },
  { itemCode: "MAST_CYPRESS", itemName: "ヒノキ", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 314, notes: null },
  { itemCode: "MAST_EGG_WHITE", itemName: "卵白", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 334, notes: null },
  { itemCode: "MAST_MILK", itemName: "牛乳", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 336, notes: null },
  { itemCode: "MAST_WHEAT", itemName: "小麦", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 337, notes: null },
  { itemCode: "MAST_SOYBEAN", itemName: "大豆", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 338, notes: null },
  { itemCode: "MAST_SHRIMP", itemName: "エビ", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 341, notes: null },
  { itemCode: "MAST_CRAB", itemName: "カニ", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 342, notes: null },
  { itemCode: "MAST_PEANUT", itemName: "ピーナッツ", category: "感染症・免疫", unit: "", referenceMin: null, referenceMax: null, displayOrder: 346, notes: null },
];

